### ISSUE TITLE
Tests logging in the console

### ISSUE THREAD

**Issue by arol** [dbyington/tworooms#9]
There's a test that is logging some data on the console, please clean it.

<img width="686" alt="captura de pantalla 2017-08-07 a les 9 12 52" src="https://user-images.githubusercontent.com/480981/29016015-cf6fecec-7b50-11e7-9251-94ce0724ce6c.png">

**Comment by dbyington** [comment]
Resolved in: Pull request #10
Commit ee191dead0e6a0e24f15606c7dc4ceff59e65198
